title: saffuan.my
description: Professional IT portfolio showcasesing technical skills, real-world problem-solving abilities, and the tangible business impact.
theme: just-the-docs

url: https://saffuan.my

aux_links:
  Template Repository: https://github.com/software70/saffuan-my
